"""Program settings"""

BACKGROUND = "light"

XLIM = -10, 10
YLIM = -10, 10
ZLIM = -10, 10

MAJOR_GRID_LINESTYLE = "-"
MAJOR_GRID_LINEWIDTH = 0.5
MAJOR_GRID_COLOR = "black"
MINOR_GRID_LINESTYLE = "-"
MINOR_GRID_LINEWIDTH = 0.5
MINOR_GRID_COLOR = "black"

WELD_SIZE_FACTOR = 1
FILLET_WELDSTYLE = "-"
GROOVE_WELDSTYLE = "--"
